"""Notification routing — email + Slack / Teams webhook fan-out.

Used when something happens that a human should know about even if
they don't have ESG Pilot open at that moment:

* A regulatory update lands in the approval queue
* A pipeline run completes (or fails)
* A risk threshold is breached
* A supplier submits new data via the portal

Design goals
------------
* **Best-effort by default** — sending a notification must never break
  the action that triggered it. Every transport catches its own
  exceptions and reports back through ``DispatchResult``.
* **No mandatory infrastructure** — SMTP credentials and webhook URLs
  are *optional*. With nothing configured, ``notify(...)`` returns a
  no-op result and the caller logs that fact. The platform still works.
* **Per-user routes** — each org admin configures the routes they want
  for the events they care about. Routes are stored on the same private
  HF Dataset that backs the rest of the auth/profile state.

Public surface
--------------
``Event``                  -> dataclass describing what happened
``DispatchResult``         -> per-route delivery status
``Route``                  -> a configured destination (email / webhook)
``RouteStore``             -> CRUD for a user's routes (HF or local fallback)
``send_email(...)``        -> low-level SMTP send (raises on failure)
``send_webhook(...)``      -> low-level POST (raises on failure)
``notify(event, ...)``     -> fan-out to all matching routes (best-effort)
"""
from __future__ import annotations

import io
import json
import logging
import os
import smtplib
import ssl
import threading
import time
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from email.message import EmailMessage
from pathlib import Path
from typing import Iterable, Optional

import requests

_log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Event taxonomy
# ---------------------------------------------------------------------------
EVENT_TYPES: tuple[str, ...] = (
    "regulatory_update_pending",
    "pipeline_run_completed",
    "pipeline_run_failed",
    "risk_threshold_breached",
    "supplier_submission_received",
    "test",
)

CHANNELS: tuple[str, ...] = ("email", "slack", "teams", "generic_webhook")


@dataclass
class Event:
    """Plain envelope passed to ``notify(...)``.

    Stays a simple dataclass on purpose — no template engine, no
    pluggable formatters. Each transport renders the event itself in a
    way that suits its medium (HTML for email, blocks for Slack, etc.).
    """
    type: str
    title: str
    summary: str
    severity: str = "info"            # info | warning | critical
    org_id: str | None = None
    actor: str | None = None
    payload: dict = field(default_factory=dict)
    url: str | None = None            # link the recipient should open

    def __post_init__(self) -> None:
        if self.type not in EVENT_TYPES:
            # Don't crash here — emit a warning and pass through. A
            # call site adding a new event type shouldn't be blocked
            # while EVENT_TYPES catches up.
            _log.warning("notifications: unknown event type %r", self.type)


@dataclass
class DispatchResult:
    """Per-route delivery outcome returned by ``notify``."""
    route_id: str
    channel: str
    ok: bool
    detail: str = ""


@dataclass
class Route:
    """A configured destination + the events it cares about.

    ``id`` is autogenerated when missing — UI code shouldn't have to
    invent stable identifiers. ``filters.event_types`` is the empty
    list to mean "all events" so a fresh route just receives everything
    by default.
    """
    id: str
    channel: str                      # one of CHANNELS
    label: str
    target: str                       # email address or webhook URL
    enabled: bool = True
    event_types: list[str] = field(default_factory=list)
    min_severity: str = "info"        # info < warning < critical
    extra: dict = field(default_factory=dict)
    created_at: str = ""

    @staticmethod
    def new(channel: str, label: str, target: str, **kwargs) -> "Route":
        return Route(
            id=uuid.uuid4().hex[:12],
            channel=channel,
            label=label,
            target=target,
            created_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
            **kwargs,
        )

    def matches(self, event: Event) -> bool:
        if not self.enabled:
            return False
        if self.event_types and event.type not in self.event_types:
            return False
        return _severity_rank(event.severity) >= _severity_rank(self.min_severity)


_SEVERITY_ORDER = {"info": 0, "warning": 1, "critical": 2}


def _severity_rank(severity: str) -> int:
    return _SEVERITY_ORDER.get((severity or "info").lower(), 0)


# ---------------------------------------------------------------------------
# Transports
# ---------------------------------------------------------------------------
def send_email(*, host: str, port: int, username: str, password: str,
               sender: str, recipients: Iterable[str],
               subject: str, body_text: str,
               body_html: str | None = None,
               use_tls: bool = True,
               timeout: float = 15.0) -> None:
    """Send a single email via SMTP. Raises on any failure.

    Kept transport-only on purpose — call sites compose the message and
    decide whether to swallow exceptions. No retries here; the caller
    holds the policy.
    """
    msg = EmailMessage()
    msg["From"] = sender
    msg["To"] = ", ".join(list(recipients))
    msg["Subject"] = subject
    msg.set_content(body_text)
    if body_html:
        msg.add_alternative(body_html, subtype="html")

    if use_tls:
        context = ssl.create_default_context()
        with smtplib.SMTP(host, port, timeout=timeout) as server:
            server.starttls(context=context)
            if username:
                server.login(username, password)
            server.send_message(msg)
    else:
        with smtplib.SMTP(host, port, timeout=timeout) as server:
            if username:
                server.login(username, password)
            server.send_message(msg)


def send_webhook(*, url: str, payload: dict,
                 headers: dict | None = None,
                 timeout: float = 10.0) -> None:
    """POST ``payload`` to ``url`` as JSON. Raises on non-2xx or transport error."""
    headers = {"Content-Type": "application/json", **(headers or {})}
    response = requests.post(url, json=payload, headers=headers, timeout=timeout)
    response.raise_for_status()


# ---------------------------------------------------------------------------
# Channel-specific renderers
# ---------------------------------------------------------------------------
def _render_email(event: Event) -> tuple[str, str, str]:
    """Return (subject, body_text, body_html) for an email render."""
    severity_emoji = {"info": "ℹ️", "warning": "⚠️", "critical": "🚨"}.get(
        event.severity, "ℹ️"
    )
    subject = f"{severity_emoji} ESG Pilot · {event.title}"
    text_lines = [event.title, "-" * len(event.title), event.summary]
    if event.url:
        text_lines += ["", f"Open in ESG Pilot: {event.url}"]
    if event.actor:
        text_lines += [f"Triggered by: {event.actor}"]
    text_body = "\n".join(text_lines)
    html_body = f"""
    <div style="font-family: -apple-system, sans-serif; max-width: 540px;
                padding: 1.25rem; border-radius: 12px;
                border: 1px solid #e2e8f0; background: #fff;">
      <h2 style="margin:0 0 .5rem 0; color:#1a202c;">{severity_emoji} {event.title}</h2>
      <p style="margin:.25rem 0; color:#4a5568;">{event.summary}</p>
      {f'<p><a href="{event.url}" style="color:#D04A02; font-weight:600;">Open in ESG Pilot →</a></p>' if event.url else ''}
      <p style="font-size:.8rem; color:#94a3b8; margin-top:1rem;">
        {f'Triggered by {event.actor} · ' if event.actor else ''}Severity: {event.severity}
      </p>
    </div>
    """
    return subject, text_body, html_body


def _render_slack(event: Event) -> dict:
    """Slack incoming-webhook payload (message + blocks)."""
    severity_emoji = {"info": ":information_source:", "warning": ":warning:",
                      "critical": ":rotating_light:"}.get(event.severity, ":bell:")
    return {
        "text": f"{severity_emoji} *{event.title}* — {event.summary}",
        "blocks": [
            {
                "type": "header",
                "text": {"type": "plain_text",
                         "text": f"{severity_emoji} {event.title}"[:150]},
            },
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": event.summary[:2900]},
            },
            *([
                {"type": "actions", "elements": [{
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Open in ESG Pilot"},
                    "url": event.url,
                }]},
            ] if event.url else []),
            {
                "type": "context",
                "elements": [{
                    "type": "mrkdwn",
                    "text": (f"_{event.actor or 'system'}_ · severity `{event.severity}` · "
                             f"`{event.type}`"),
                }],
            },
        ],
    }


def _render_teams(event: Event) -> dict:
    """MS Teams Incoming Webhook payload (legacy MessageCard form)."""
    severity_color = {"info": "0078D4", "warning": "FFB600",
                      "critical": "D04A02"}.get(event.severity, "0078D4")
    card = {
        "@type": "MessageCard",
        "@context": "https://schema.org/extensions",
        "themeColor": severity_color,
        "summary": event.title[:128],
        "title": event.title,
        "text": event.summary,
        "sections": [
            {
                "facts": [
                    {"name": "Type", "value": event.type},
                    {"name": "Severity", "value": event.severity},
                    *([{"name": "Triggered by", "value": event.actor}]
                      if event.actor else []),
                ],
            },
        ],
    }
    if event.url:
        card["potentialAction"] = [{
            "@type": "OpenUri",
            "name": "Open in ESG Pilot",
            "targets": [{"os": "default", "uri": event.url}],
        }]
    return card


def _render_generic(event: Event) -> dict:
    """Plain JSON shape for a generic webhook (custom integrations)."""
    return {
        "type": event.type,
        "title": event.title,
        "summary": event.summary,
        "severity": event.severity,
        "actor": event.actor,
        "org_id": event.org_id,
        "url": event.url,
        "payload": event.payload,
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }


# ---------------------------------------------------------------------------
# Route store
# ---------------------------------------------------------------------------
DEFAULT_DATASET = os.getenv("ESG_AUTH_DATASET", "isayan58/esg-copilot-auth")
ROUTES_DIR_IN_REPO = "notification_routes"
LOCAL_FALLBACK_DIR = Path("data") / "notification_routes"
CACHE_TTL_SECONDS = 60

try:
    from huggingface_hub import HfApi, hf_hub_download
    from huggingface_hub.utils import (
        EntryNotFoundError,
        HfHubHTTPError,
        RepositoryNotFoundError,
    )
    _HAS_HF = True
except Exception:  # pragma: no cover
    HfApi = None  # type: ignore
    hf_hub_download = None  # type: ignore
    _HAS_HF = False


def _resolve_token() -> Optional[str]:
    for name in ("HF_TOKEN", "HF_API_TOKEN", "HUGGING_FACE_HUB_TOKEN"):
        value = os.getenv(name)
        if value:
            return value.strip()
    return None


def _safe_owner(owner: str) -> str:
    import re
    cleaned = re.sub(r"[^a-zA-Z0-9_.\-]", "_", (owner or "").strip())
    return cleaned[:64] or "anonymous"


class RouteStore:
    """CRUD for notification routes, scoped to an *owner* (org_id by default).

    Mirrors the shape of ``utils.run_store`` and ``utils.profile_store``
    so the same persistence semantics (HF dataset preferred, local
    fallback, structured diagnostic) apply uniformly.
    """

    def __init__(self, dataset_repo: str = DEFAULT_DATASET):
        self._dataset = dataset_repo
        self._token = _resolve_token()
        self._api = HfApi(token=self._token) if (_HAS_HF and self._token) else None
        self._lock = threading.RLock()
        self._cache: dict[str, tuple[list[Route], float]] = {}
        self._resolved_backend: Optional[str] = None
        self._last_error: Optional[str] = None

    # -- Diagnostic --------------------------------------------------------
    def diagnostic(self) -> dict:
        return {
            "backend": self._resolved_backend,
            "has_token": bool(self._token),
            "dataset": self._dataset,
            "last_error": self._last_error,
        }

    # -- Public API --------------------------------------------------------
    def list_routes(self, owner: str) -> list[Route]:
        owner = _safe_owner(owner)
        with self._lock:
            cached = self._cache.get(owner)
            if cached and (time.time() - cached[1]) < CACHE_TTL_SECONDS:
                return [Route(**asdict(r)) for r in cached[0]]
            records = self._load_raw(owner)
            routes = [_route_from_record(r) for r in records]
            self._cache[owner] = (list(routes), time.time())
            return routes

    def add_route(self, owner: str, route: Route) -> Route:
        owner = _safe_owner(owner)
        with self._lock:
            routes = self.list_routes(owner)
            routes.append(route)
            self._save_raw(owner, [asdict(r) for r in routes])
            self._cache[owner] = (list(routes), time.time())
        return route

    def remove_route(self, owner: str, route_id: str) -> bool:
        owner = _safe_owner(owner)
        with self._lock:
            routes = self.list_routes(owner)
            new_routes = [r for r in routes if r.id != route_id]
            if len(new_routes) == len(routes):
                return False
            self._save_raw(owner, [asdict(r) for r in new_routes])
            self._cache[owner] = (list(new_routes), time.time())
            return True

    def update_route(self, owner: str, route_id: str, patch: dict) -> Optional[Route]:
        owner = _safe_owner(owner)
        with self._lock:
            routes = self.list_routes(owner)
            updated: Optional[Route] = None
            for idx, r in enumerate(routes):
                if r.id == route_id:
                    new_kwargs = {**asdict(r), **(patch or {})}
                    updated = _route_from_record(new_kwargs)
                    routes[idx] = updated
                    break
            if updated is None:
                return None
            self._save_raw(owner, [asdict(r) for r in routes])
            self._cache[owner] = (list(routes), time.time())
            return updated

    # -- Backend internals -------------------------------------------------
    def _path_in_repo(self, owner: str) -> str:
        return f"{ROUTES_DIR_IN_REPO}/{owner}.json"

    def _local_path(self, owner: str) -> Path:
        return LOCAL_FALLBACK_DIR / f"{owner}.json"

    def _load_raw(self, owner: str) -> list[dict]:
        if self._api is not None:
            try:
                local_path = hf_hub_download(
                    repo_id=self._dataset,
                    repo_type="dataset",
                    filename=self._path_in_repo(owner),
                    token=self._token,
                )
                self._resolved_backend = "hf_dataset"
                self._last_error = None
                with open(local_path, "r", encoding="utf-8") as fh:
                    data = json.load(fh)
                return data if isinstance(data, list) else []
            except (EntryNotFoundError, RepositoryNotFoundError,
                    HfHubHTTPError, ValueError):
                self._resolved_backend = "hf_dataset"
                return []
            except Exception as exc:  # noqa: BLE001
                self._last_error = f"{type(exc).__name__}: {exc}"
        # Local fallback
        path = self._local_path(owner)
        self._resolved_backend = "local_json"
        if not path.is_file():
            return []
        try:
            with open(path, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            return data if isinstance(data, list) else []
        except (OSError, json.JSONDecodeError):
            return []

    def _save_raw(self, owner: str, records: list[dict]) -> None:
        payload = json.dumps(records, indent=2, ensure_ascii=False).encode("utf-8")
        if self._api is not None and self._resolved_backend in (None, "hf_dataset"):
            try:
                self._api.create_repo(
                    repo_id=self._dataset, repo_type="dataset",
                    private=True, exist_ok=True,
                )
                self._api.upload_file(
                    path_or_fileobj=io.BytesIO(payload),
                    path_in_repo=self._path_in_repo(owner),
                    repo_id=self._dataset, repo_type="dataset",
                    commit_message=f"Update notification routes for {owner}",
                )
                self._resolved_backend = "hf_dataset"
                self._last_error = None
                return
            except Exception as exc:  # noqa: BLE001
                self._last_error = f"{type(exc).__name__}: {exc}"
        # Local fallback
        path = self._local_path(owner)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "wb") as fh:
            fh.write(payload)
        self._resolved_backend = "local_json"


def _route_from_record(record: dict) -> Route:
    """Construct a Route from a JSON dict, ignoring unknown fields.

    Same defensive pattern as ``_user_from_record`` — old persisted
    records can predate new fields, and a dataclass kwargs explosion
    would brick the load.
    """
    known = {f.name for f in Route.__dataclass_fields__.values()}  # type: ignore[attr-defined]
    payload = {k: v for k, v in (record or {}).items() if k in known}
    payload.setdefault("id", uuid.uuid4().hex[:12])
    payload.setdefault("channel", "email")
    payload.setdefault("label", "Untitled route")
    payload.setdefault("target", "")
    return Route(**payload)


_STORE: Optional[RouteStore] = None


def get_route_store() -> RouteStore:
    global _STORE
    if _STORE is None:
        _STORE = RouteStore()
    return _STORE


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
def _smtp_config_from_env() -> Optional[dict]:
    """Pick up SMTP settings from env vars (the same pattern as HF_TOKEN).

    All-or-nothing: missing host / port / sender returns None and the
    email channel is skipped. Keeps configuration explicit — we never
    silently fall through to a localhost smtpd nobody asked for.
    """
    host = os.getenv("ESG_SMTP_HOST")
    sender = os.getenv("ESG_SMTP_SENDER")
    port = os.getenv("ESG_SMTP_PORT", "587")
    if not host or not sender:
        return None
    try:
        port_i = int(port)
    except ValueError:
        return None
    return {
        "host": host,
        "port": port_i,
        "username": os.getenv("ESG_SMTP_USER", ""),
        "password": os.getenv("ESG_SMTP_PASS", ""),
        "sender": sender,
        "use_tls": os.getenv("ESG_SMTP_TLS", "1") not in ("0", "false", "False"),
    }


def _dispatch_to(route: Route, event: Event) -> DispatchResult:
    """Send ``event`` to a single ``route``, capturing any error.

    Each transport has its own try/except so one bad route can't block
    a different route in the same fan-out. The result detail string is
    short enough to render inline in the route table.
    """
    try:
        if route.channel == "email":
            smtp = _smtp_config_from_env()
            if not smtp:
                return DispatchResult(
                    route_id=route.id, channel=route.channel, ok=False,
                    detail="No SMTP config (set ESG_SMTP_HOST/SENDER/...).",
                )
            subject, text, html = _render_email(event)
            send_email(
                **smtp,
                recipients=[route.target],
                subject=subject,
                body_text=text,
                body_html=html,
            )
            return DispatchResult(route_id=route.id, channel="email", ok=True,
                                   detail="sent")
        elif route.channel == "slack":
            send_webhook(url=route.target, payload=_render_slack(event))
            return DispatchResult(route_id=route.id, channel="slack", ok=True,
                                   detail="posted")
        elif route.channel == "teams":
            send_webhook(url=route.target, payload=_render_teams(event))
            return DispatchResult(route_id=route.id, channel="teams", ok=True,
                                   detail="posted")
        elif route.channel == "generic_webhook":
            send_webhook(url=route.target, payload=_render_generic(event))
            return DispatchResult(route_id=route.id, channel="generic_webhook",
                                   ok=True, detail="posted")
        else:
            return DispatchResult(route_id=route.id, channel=route.channel,
                                   ok=False, detail=f"Unknown channel: {route.channel}")
    except Exception as exc:  # noqa: BLE001 — best effort across all transports
        return DispatchResult(
            route_id=route.id, channel=route.channel, ok=False,
            detail=f"{type(exc).__name__}: {exc}"[:200],
        )


def notify(event: Event, *, owner: str | None = None,
           routes: list[Route] | None = None) -> list[DispatchResult]:
    """Fan-out ``event`` to every matching route. Never raises.

    Either ``owner`` (resolves to ``RouteStore``) or an explicit
    ``routes`` list must be provided. With neither, the function
    short-circuits to an empty result so callers in code paths without
    a configured owner still work.
    """
    if routes is None:
        if not owner:
            return []
        try:
            routes = get_route_store().list_routes(owner)
        except Exception as exc:  # noqa: BLE001
            _log.warning("notifications: route lookup failed: %s", exc)
            return []

    matching = [r for r in routes if r.matches(event)]
    if not matching:
        return []

    results: list[DispatchResult] = []
    for route in matching:
        results.append(_dispatch_to(route, event))
    return results


__all__ = [
    "EVENT_TYPES", "CHANNELS",
    "Event", "DispatchResult", "Route",
    "RouteStore", "get_route_store",
    "send_email", "send_webhook",
    "notify",
]
